TenderSystem/TenderManagementSystem/Controllers/BidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TenderManagementSystem.Models;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;
using System.Text.RegularExpressions;
using System.Net.Mail;

namespace TenderManagementSystem.Controllers
{
    public class BidController : Controller
    {

        // View all bid data
        public ActionResult ViewBids()
        {

            var bidList = new List<Bid>();
            string userrole = "";
            string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;

            if (Session["Email"] != null)
            {
                using (SqlConnection con2 = new SqlConnection(constr))
                {
                    con2.Open();

                    String sql2 = "SELECT UserRole FROM SystemUser WHERE Email = @Email";
                    SqlCommand cmd2 = new SqlCommand(sql2, con2);
                    cmd2.Parameters.AddWithValue("@Email", Session["Email"]);

                    SqlDataReader sdr2 = cmd2.ExecuteReader();
                    while (sdr2.Read())
                    {
                        userrole = sdr2["UserRole"].ToString().Trim();
                    }

                    con2.Close();
                }
            }


            if (userrole.Contains("Officer") || userrole.Contains("Director"))
            {
                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    String sql = "SELECT Bid.Id, Bid.BidID, Bid.DateSubmitted, Bid.Price, Bid.TenderID, " +
                        "Bid.UserID, Bid.Description, Bid.Status FROM Bid";
                    SqlCommand cmd = new SqlCommand(sql, con);

                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        var bid = new Bid();
                        bid.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                        bid.BidID = sdr["BidID"].ToString().Trim();
                        bid.DateSubmitted = sdr["DateSubmitted"].ToString().Trim();
                        bid.TenderID = sdr["TenderID"].ToString().Trim();
                        bid.Price = sdr["Price"].ToString().Trim();
                        bid.UserID = sdr["UserID"].ToString().Trim();
                        bid.Status = sdr["Status"].ToString().Trim();
                        bid.Description = sdr["Description"].ToString().Trim();
                        bidList.Add(bid);
                    }

                    con.Close();
                }
                if (Session["Email"] != null)
                {
                    return View(bidList);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            else
            {
                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    String sql = "SELECT Bid.Id, Bid.BidID, Bid.DateSubmitted, Bid.Price, Bid.TenderID, Bid.UserID," +
                        "Bid.Status, Bid.Description FROM Bid" +
                        " WHERE UserID IN (SELECT UserID FROM SystemUser WHERE Email = @Email)";
                    SqlCommand cmd = new SqlCommand(sql, con);
                    cmd.Parameters.AddWithValue("@Email", Session["Email"]);

                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        var bid = new Bid();
                        bid.Id = Convert.ToInt32(sdr["Id"].ToString());
                        bid.BidID = sdr["BidID"].ToString();
                        bid.DateSubmitted = sdr["DateSubmitted"].ToString();
                        bid.TenderID = sdr["TenderID"].ToString();
                        bid.Price = sdr["Price"].ToString();
                        bid.Description = sdr["Description"].ToString();
                        bid.UserID = sdr["UserID"].ToString();
                        bid.Status = sdr["Status"].ToString();
                        bidList.Add(bid);
                    }

                    con.Close();
                }
                if (Session["Email"] != null)
                {
                    return View(bidList);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }


        }


        // View own bid data
        public ActionResult ViewMyBids()
        {

            var bidList = new List<Bid>();
            string userrole = "";
            string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;

            if (Session["Email"] != null)
            {
                using (SqlConnection con2 = new SqlConnection(constr))
                {
                    con2.Open();

                    String sql2 = "SELECT UserRole FROM SystemUser WHERE Email = @Email";
                    SqlCommand cmd2 = new SqlCommand(sql2, con2);
                    cmd2.Parameters.AddWithValue("@Email", Session["Email"]);

                    SqlDataReader sdr2 = cmd2.ExecuteReader();
                    while (sdr2.Read())
                    {
                        userrole = sdr2["UserRole"].ToString().Trim();
                    }

                    con2.Close();
                }
            }


            if (userrole.Contains("Officer") || userrole.Contains("Director"))
            {
                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    String sql = "SELECT Bid.Id, Bid.BidID, Bid.DateSubmitted, Bid.Price, Bid.TenderID, " +
                        "Bid.UserID, Bid.Description, Bid.Status FROM Bid ORDER BY cast(Bid.Price as decimal) DESC";
                    SqlCommand cmd = new SqlCommand(sql, con);

                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        var bid = new Bid();
                        bid.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                        bid.BidID = sdr["BidID"].ToString().Trim();
                        bid.DateSubmitted = sdr["DateSubmitted"].ToString().Trim();
                        bid.TenderID = sdr["TenderID"].ToString().Trim();
                        bid.Price = sdr["Price"].ToString().Trim();
                        bid.UserID = sdr["UserID"].ToString().Trim();
                        bid.Status = sdr["Status"].ToString().Trim();
                        bid.Description = sdr["Description"].ToString().Trim();
                        bidList.Add(bid);
                    }

                    con.Close();
                }
                if (Session["Email"] != null)
                {
                    return View(bidList);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
            else
            {
                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    String sql = "SELECT Bid.Id, Bid.BidID, Bid.DateSubmitted, Bid.Price, Bid.TenderID, Bid.UserID," +
                        "Bid.Status, Bid.Description FROM Bid" +
                        " WHERE UserID IN (SELECT UserID FROM SystemUser WHERE Email = @Email) ORDER BY Bid.DateSubmitted DESC";
                    SqlCommand cmd = new SqlCommand(sql, con);
                    cmd.Parameters.AddWithValue("@Email", Session["Email"]);

                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        var bid = new Bid();
                        bid.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                        bid.BidID = sdr["BidID"].ToString().Trim();
                        bid.DateSubmitted = sdr["DateSubmitted"].ToString().Trim();
                        bid.TenderID = sdr["TenderID"].ToString().Trim();
                        bid.Price = sdr["Price"].ToString().Trim();
                        bid.Description = sdr["Description"].ToString().Trim();
                        bid.UserID = sdr["UserID"].ToString().Trim();
                        bid.Status = sdr["Status"].ToString().Trim();
                        bidList.Add(bid);
                    }

                    con.Close();
                }
                if (Session["Email"] != null)
                {
                    return View(bidList);
                }
                else
                {
                    return RedirectToAction("Login", "Home");
                }
            }
        }


        public ActionResult AddBidDetails(int? id)
        {
            int TenderID = Convert.ToInt32(id);
            var bid = new Bid();
            List<SelectListItem> showroomList = new List<SelectListItem>();

            if (Session["Email"] != null)
            {
                string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;
                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    String sql = "SELECT Id, TenderID, TenderName,TenderDate, Image FROM Tender WHERE Id = @Id";
                    SqlCommand cmd = new SqlCommand(sql, con);
                    cmd.Parameters.AddWithValue("@Id", TenderID);

                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        bid.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                        bid.TenderID = sdr["TenderID"].ToString().Trim();

TenderSystem/TenderManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tender Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">


                    @if ((ViewContext.RouteData.Values["action"].ToString() != "ViewCustomers") &&
                    (ViewContext.RouteData.Values["action"].ToString() != "ViewTenders") &&
                    (ViewContext.RouteData.Values["action"].ToString() != "AddTender") &&
                    (ViewContext.RouteData.Values["action"].ToString() != "ViewBids") &&
                    (ViewContext.RouteData.Values["action"].ToString() != "ViewDetails") &&
                    (ViewContext.RouteData.Values["action"].ToString() != "ViewTenderDetails") &&
                    (ViewContext.RouteData.Values["action"].ToString() != "EditCustomer"))
                    {

                        <li>@Html.ActionLink("Tenders", "Tenders", "Tender")</li>
                        if (ViewContext.HttpContext.Session.Count == 1)
                        {
                            <li>@Html.ActionLink("View My Bids", "ViewMyBids", "Bid")</li>
                        }
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact Us", "ContactUs", "Home")</li>
                    } else if ((ViewContext.RouteData.Values["action"].ToString() == "ViewCustomers") ||
                       (ViewContext.RouteData.Values["action"].ToString() == "ViewTenders") ||
                       (ViewContext.RouteData.Values["action"].ToString() == "AddTender") ||
                       (ViewContext.RouteData.Values["action"].ToString() == "ViewBids") ||
                       (ViewContext.RouteData.Values["action"].ToString() != "ViewMyBids") ||
                       (ViewContext.RouteData.Values["action"].ToString() == "EditTender") ||
                       (ViewContext.RouteData.Values["action"].ToString() != "ViewDetails") ||
                       (ViewContext.RouteData.Values["action"].ToString() != "AddBidDetails") ||
                       (ViewContext.RouteData.Values["action"].ToString() == "EditCustomer") ||
                            (ViewContext.RouteData.Values["action"].ToString() != "ViewTenderDetails"))
                    {
                            <li>@Html.ActionLink("View Customers", "ViewCustomers", "Home")</li>
                            <li>@Html.ActionLink("View Tenders", "ViewTenders", "Tender")</li>
                            <li>@Html.ActionLink("Add Tenders", "AddTender", "Tender")</li>
                            <li>@Html.ActionLink("View Bids", "ViewBids", "Bid")</li>
                    }

                    </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (ViewContext.HttpContext.Session.Count == 1)
                    {
                        <li>@Html.ActionLink("Edit Profile", "EditProfile", "Home")</li>
                        <li>@Html.ActionLink("Logout", "Login", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                        <li>@Html.ActionLink("Sign Up", "Register", "Home")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>