TenderSystem/TenderManagementSystem/Models/Tender.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace TenderManagementSystem.Models
{
    public class Tender
    {
        // Creating get and set methods for Id
        public int Id { get; set; }

        // Creating get and set methods for TenderID
        public string TenderID { get; set; }

        // Creating get and set methods for TenderName
        public string TenderName { get; set; }

        // Creating get and set methods for Description
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        // Creating get and set methods for TenderDate
        public string TenderDate { get; set; }
        // Creating get and set methods for BidsList
        public List<Bid> BidsList { get; set; }

        // Creating get and set methods for Image
        public System.Web.HttpPostedFileBase Image { get; set; }
        public string ImageURL { get; set; }

        // Creating get and set methods for UserRole
        public string UserRole { get; set; }

    }
}

TenderSystem/TenderManagementSystem/Controllers/TenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TenderManagementSystem.Models;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;
using System.Text.RegularExpressions;
using System.IO;
using System.Net.Mail;

namespace TenderManagementSystem.Controllers
{
    public class TenderController : Controller
    {
        // View the tenders page
        public ActionResult Tenders()
        {
            var tenderList = new List<Tender>();

            string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                con.Open();

                String sql = "SELECT Id, TenderID, TenderName, TenderDate, Description, Image FROM Tender ORDER BY TenderDate DESC";
                SqlCommand cmd = new SqlCommand(sql, con);

                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    var tenderdate = DateTime.Parse((sdr["TenderDate"].ToString().Split()[0]).Replace("-", "/")).Date;
                    DateTime datenow = DateTime.Now.Date;

                    var tender = new Tender();
                    tender.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                    tender.TenderID = sdr["TenderID"].ToString().Trim();
                    tender.TenderName = sdr["TenderName"].ToString().Trim();
                    tender.TenderDate = sdr["TenderDate"].ToString().Trim();
                    tender.Description = sdr["Description"].ToString().Trim();
                    tender.ImageURL = "~/Content/Images/" + sdr["Image"].ToString().Trim();
                    if((tenderdate > datenow) || (tenderdate == datenow))
                    {
                        tenderList.Add(tender);
                    }
                    
                }

                con.Close();
            }
            return View(tenderList);

        }

        // View all the tender data
        public ActionResult ViewTenders()
        {

            var tenderList = new List<Tender>();
            var bidList = new List<Bid>();

            string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                con.Open();

                String sql = "SELECT Id, TenderID, TenderName, TenderDate, Description, Image FROM Tender ORDER BY TenderDate DESC";
                SqlCommand cmd = new SqlCommand(sql, con);

                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {

                    var tender = new Tender();
                    tender.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                    tender.TenderID = sdr["TenderID"].ToString().Trim();
                    tender.TenderName = sdr["TenderName"].ToString().Trim();
                    tender.TenderDate = sdr["TenderDate"].ToString().Trim();
                    tender.Description = sdr["Description"].ToString().Trim();
                    tender.ImageURL = "~/Content/Images/" + sdr["Image"].ToString().Trim();

                    
                    tenderList.Add(tender);
                }

                con.Close();
            }
            foreach (Tender temptender in tenderList)
            {

                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    String sql = "SELECT Bid.Id, Bid.BidID, Bid.DateSubmitted, Bid.Price, Bid.TenderID, Bid.UserID, " +
                        "Bid.Description, Bid.Status FROM Bid WHERE Bid.TenderID = @TenderID";
                    SqlCommand cmd = new SqlCommand(sql, con);
                    cmd.Parameters.AddWithValue("@TenderID", temptender.TenderID);

                    SqlDataReader sdr = cmd.ExecuteReader();
                    while (sdr.Read())
                    {
                        var bid = new Bid();
                        bid.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                        bid.BidID = sdr["BidID"].ToString().Trim();
                        bid.DateSubmitted = sdr["DateSubmitted"].ToString().Trim();
                        bid.TenderID = sdr["TenderID"].ToString().Trim();
                        bid.Price = sdr["Price"].ToString().Trim();
                        bid.UserID = sdr["UserID"].ToString().Trim();
                        bid.Description = sdr["Description"].ToString().Trim();
                        bid.Status = sdr["Status"].ToString().Trim();
                        bidList.Add(bid);
                    }

                    temptender.BidsList = bidList;
                    con.Close();
                }
            }
            if (Session["Email"] != null)
            {
                return View(tenderList);
            }
            else
            {
                return RedirectToAction("Home/Login");
            }

        }

        // View add tender page
        public ActionResult AddTender()
        {
            return View();
        }

        // Get the tender model and insert new tender details to the tender table
        [HttpPost]
        public ActionResult AddTender(Tender tender)
        {

            foreach (var modelValue in ModelState.Values)
            {
                modelValue.Errors.Clear();
            }


            Guid guid = Guid.NewGuid();
            tender.TenderID = guid.ToString();
            Random random = new Random();
            tender.Id = random.Next();

            if (string.IsNullOrEmpty(tender.TenderName))
            {
                ModelState.AddModelError("TenderName", "This field cannot be empty ");
            }
            if (string.IsNullOrEmpty(tender.Description))
            {
                ModelState.AddModelError("Description", "This field cannot be empty ");
            }

            if (ModelState.IsValid)
            {
                //byte[] image = new byte[tender.Image.ContentLength];
                //tender.Image.InputStream.Read(image, 0, image.Length);

                string newfilename;
                if (tender.Image != null)
                {
                    var filename = Path.GetFileName(tender.Image.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), filename);
                    if(System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    newfilename = tender.Id + System.IO.Path.GetExtension(tender.Image.FileName);
                    tender.Image.SaveAs(System.IO.Path.Combine(Server.MapPath("~/Content/Images/"), newfilename));
                }
                else
                {
                    newfilename = "noimage.jpg";
                }


                string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;

                using (SqlConnection con = new SqlConnection(constr))
                {
                    con.Open();

                    SqlCommand com = new SqlCommand("INSERT INTO Tender(Id, TenderID, TenderName, TenderDate, Description, Image) " +
                        "VALUES(@Id, @TenderID, @TenderName, @TenderDate, @Image)");
                    com.CommandType = CommandType.Text;
                    com.Connection = con;

                    com.Parameters.AddWithValue("@Id", tender.Id);
                    com.Parameters.AddWithValue("@TenderID", tender.TenderID);
                    com.Parameters.AddWithValue("@TenderName", tender.TenderName);
                    com.Parameters.AddWithValue("@TenderDate", tender.TenderDate);
                    com.Parameters.AddWithValue("@Description", tender.Description);
                    com.Parameters.AddWithValue("@Image", newfilename);

                    com.ExecuteReader();
                    con.Close();
                }

                return RedirectToAction("ViewTenders");
            }
            else
            {
                return View("AddTender", tender);
            }


        }


        public ActionResult ViewTenderDetails(int? id)
        {
            int TenderID = Convert.ToInt32(id);
            var tender = new Tender();
            var bidList = new List<Bid>();

            string constr = ConfigurationManager.ConnectionStrings["WebProjectDb"].ConnectionString;
            using (SqlConnection con = new SqlConnection(constr))
            {
                con.Open();

                String sql = "SELECT Id, TenderID, TenderName, TenderDate, Description, Image FROM Tender WHERE Id = @Id";
                SqlCommand cmd = new SqlCommand(sql, con);
                cmd.Parameters.AddWithValue("@Id", TenderID);

                SqlDataReader sdr = cmd.ExecuteReader();
                while (sdr.Read())
                {
                    tender.Id = Convert.ToInt32(sdr["Id"].ToString().Trim());
                    tender.TenderID = sdr["TenderID"].ToString().Trim();
                    tender.TenderName = sdr["TenderName"].ToString().Trim();
                    tender.TenderDate = sdr["TenderDate"].ToString().Trim();
                    tender.Description = sdr["Description"].ToString().Trim();
                    tender.ImageURL = "~/Content/Images/" + sdr["Image"].ToString().Trim();
                }

                con.Close();
            }

            using (SqlConnection con = new SqlConnection(constr))
            {
                con.Open();

                String sql = "SELECT Bid.Id, Bid.BidID, Bid.DateSubmitted, Bid.Price, Bid.TenderID, Bid.UserID, " +
                        "Bid.Description, Bid.Status FROM Bid WHERE Bid.TenderID = @TenderID ORDER BY cast(Bid.Price as decimal) DESC";
                SqlCommand cmd = new SqlCommand(sql, con);

TenderSystem/TenderManagementSystem/Views/Tender/AddTender.cshtml
@model TenderManagementSystem.Models.Tender

@{
    ViewBag.Title = "AddTender";
}

<h3>Add New Product</h3>


@using (Html.BeginForm("AddTender", "Tender", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TenderName, "Tender Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenderDate, "Tender Date (MM/DD/YYYY)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, "Upload", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Image, new { type = "file", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TenderSystem/TenderManagementSystem/Views/Tender/EditTender.cshtml
@model TenderManagementSystem.Models.Tender

@{
    ViewBag.Title = "EditTender";
}

<h3>Edit Tender Details</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.TenderID)


    <div class="form-group">
        @Html.LabelFor(model => model.Id, "ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenderID, "Tender ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderID, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
            @Html.ValidationMessageFor(model => model.TenderID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TenderName, "Tender Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenderDate, "Tender Date (MM/DD/YYYY)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @rows = 10 } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "ViewTenders")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TenderSystem/TenderManagementSystem/Views/Tender/Tenders.cshtml
@model IEnumerable<TenderManagementSystem.Models.Tender>
@{
    ViewBag.Title = "Tenders";
}
<h3>Tenders</h3>
<hr />
@foreach (var item in Model)
{
    <div class="col-md-4">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <h4>@item.TenderName</h4>
                    <br />
                    <h5 style="text-align: left; padding: 5px; padding-left: 20px; padding-right: 20px">Tender Code: @item.TenderID</h5>
                    <h5 style="text-align: left; padding: 5px; padding-left: 20px; padding-right: 20px ">Tender Date: @item.TenderDate</h5>
                    <h5 style="text-align: left; padding: 5px; padding-left: 20px; padding-right: 20px ">Description: @item.Description</h5>
                    <br /><br />
                    <a href="@Url.Content(@item.ImageURL)" target="_blank">View PDF</a> |
                    @Html.ActionLink("Bid for Tender", "AddBidDetails", "Bid", new { id = item.Id }, null)
                </div>
            </div>
        </div>
        <br />
    </div>
}

TenderSystem/TenderManagementSystem/Views/Tender/ViewTenderDetails.cshtml
@model TenderManagementSystem.Models.Tender

@{
    ViewBag.Title = "ViewTenderDetails";
}

<script>
    function AcceptBid(id) {
        location.href = "/Tender/AcceptBid/" + id;
    }
    function RejectBid(id) {
        location.href = "/Tender/RejectBid/" + id;
    }
    function EvaluateBid(id) {
        location.href = "/Tender/EvaluateBid/" + id;
    }
</script>

<h3>View Tender Details</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Id, "ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenderID, "Tender ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TenderName, "Tender Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenderDate, "TenderDate", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenderDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageURL, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <a href="@Url.Content(Model.ImageURL)" target="_blank">File</a>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete Tender" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div class="row">
    <div class="container">
        <h3>Bids</h3>
        <h5>*Note that the first bid is the highest bid submitted for this tender</h5>
        <table class="table">
            <tr>
                <th>
                    Bid Id
                </th>
                <th>
                    Date Submitted
                </th>
                <th>
                    Price
                </th>
                <th>
                    Current Status
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var item in Model.BidsList)
            {
                <tr>
                    <td>
                        @item.BidID
                    </td>
                    <td>
                        @item.DateSubmitted
                    </td>
                    <td>
                        @item.Price
                    </td>
                    @if (Model.UserRole.Contains("Director"))
                    {
                        if (item.Status.Contains("Pending"))
                        {
                            <td style="color:darkorange">
                                @item.Status
                            </td>
                            <td></td>
                        }
                        if (item.Status.Contains("Evaluated"))
                        {
                            <td style="color: dodgerblue">
                                @item.Status
                            </td>
                            <td>
                                <input type="button" class="btn btn-default" value="Accept"
                                       onclick="AcceptBid(@item.Id)" style="color:white; background-color:forestgreen" />
                            </td>
                        }
                        if (item.Status.Contains("Accepted"))
                        {
                            <td style="color:forestgreen">
                                @item.Status
                            </td>
                            <td>
                                <input type="button" class="btn btn-default" value="Reject"
                                       onclick="RejectBid(@item.Id)" style="color:white; background-color:red" />
                            </td>
                        }
                        if (item.Status.Contains("Rejected"))
                        {
                            <td style="color:red">
                                @item.Status
                            </td>
                            <td></td>
                        }
                    }
                    else
                    {
                        if (item.Status.Contains("Pending"))
                        {
                            <td style="color:darkorange">
                                @item.Status
                            </td>
                            <td>
                                <input type="button" class="btn btn-default" value="Evaluate"
                                       onclick="EvaluateBid(@item.Id)" style="color:white; background-color:dodgerblue" />
                            </td>
                        }
                        if (item.Status.Contains("Evaluated"))
                        {
                            <td style="color:darkorange">
                                @item.Status
                            </td>
                            <td></td>
                        }
                        if (item.Status.Contains("Accepted"))
                        {
                            <td style="color:forestgreen">
                                @item.Status
                            </td>
                            <td></td>
                        }
                        if (item.Status.Contains("Rejected"))
                        {
                            <td style="color:red">
                                @item.Status
                            </td>
                            <td></td>
                        }
                    }

                    <td>
                        <a href="@Url.Action("ViewBidDetails", "Bid",new { id=item.Id } )">View</a> |
                        <a href="@Url.Action("ViewBidDetails", "Bid",new { id=item.Id } )">Delete</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "ViewTenders")
</div>

TenderSystem/TenderManagementSystem/Views/Tender/ViewTenders.cshtml
@model IEnumerable<TenderManagementSystem.Models.Tender>
@{
    ViewBag.Title = "ViewTenders";
}
<script>
    function SendEmails(tenderid) {
        location.href = "/Tender/EmailBidders/" + tenderid;
    }
</script>
<div class="row">
    <div class="container">
        <h3>Tender Details</h3>
        <table class="table">
            <tr>
                <th>
                    Tender Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    TenderDate
                </th>
                <th>Email Bidders</th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @item.TenderID
                </td>
                <td>
                    @item.TenderName
                </td>
                <td>
                    @item.TenderDate
                </td>
                <td>
                    <input type="button" class="btn btn-default" value="Email Bidders"
                           onclick="SendEmails(@item.Id)" style="color:white; background-color:dodgerblue" />
                </td>
                <td>
                    @Html.ActionLink("View", "ViewTenderDetails", new { id = item.Id }) |
                    @Html.ActionLink("Edit", "EditTender", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "ViewTenderDetails", new { id = item.Id })
                </td>
            </tr>
            }

        </table>
    </div>
</div>